[CmdletBinding()]
param([switch]$Apply,[string]$ConfirmProjectId="",[ValidatePattern('^[a-f0-9]{32}$')][string]$CloudflareZoneId="",[ValidateRange(30,3600)][int]$CertificateTimeoutSeconds=900,[ValidateRange(5,60)][int]$CertificatePollIntervalSeconds=10)
. (Join-Path $PSScriptRoot "Common.ps1")
$m=Get-MatchBaseStagingRegionMigration; $project=[string]$m.ProjectId; $main=[string]$m.Hostname; $canary=[string]$m.CanaryHostname
$ranges=@("173.245.48.0/20","103.21.244.0/22","103.22.200.0/22","103.31.4.0/22","141.101.64.0/18","108.162.192.0/18","190.93.240.0/20","188.114.96.0/20","197.234.240.0/22","198.41.128.0/17","162.158.0.0/15","104.16.0.0/13","104.24.0.0/14","172.64.0.0/13","131.0.72.0/22")
for($i=0;$i-lt $ranges.Count;$i++){ $p=2000+$i;$e="inIpRange(origin.ip, '$($ranges[$i])') && request.headers['host'].lower() == '$canary'";Write-GcloudPlan -Arguments @("compute","security-policies","rules","create","$p","--project=$project","--security-policy=$($m.SecurityPolicy)","--action=allow","--expression=$e","--quiet") }
Write-GcloudPlan -Arguments @("certificate-manager","dns-authorizations","create",[string]$m.MainDnsAuthorization,"--project=$project","--location=global","--domain=$main","--type=FIXED_RECORD","--labels=matchbase-governed=true,matchbase-scope=staging-canary-edge")
Write-GcloudPlan -Arguments @("certificate-manager","dns-authorizations","create",[string]$m.CanaryDnsAuthorization,"--project=$project","--location=global","--domain=$canary","--type=FIXED_RECORD","--labels=matchbase-governed=true,matchbase-scope=staging-canary-edge")
Write-Output "Cloudflare plan: create/update the two exact DNS-authorization CNAMEs as DNS-only; keep the application A proxied to the governed IPv4 and require public A/AAAA; preserve SSL=strict."
Write-GcloudPlan -Arguments @("certificate-manager","certificates","create",[string]$m.CanaryCertificateName,"--project=$project","--location=global","--domains=$main,$canary","--dns-authorizations=$($m.MainDnsAuthorization),$($m.CanaryDnsAuthorization)","--labels=matchbase-governed=true,matchbase-scope=staging-canary-edge")
Write-GcloudPlan -Arguments @("certificate-manager","maps","create",[string]$m.CertificateMap,"--project=$project","--location=global","--labels=matchbase-governed=true,matchbase-scope=staging-canary-edge")
Write-GcloudPlan -Arguments @("certificate-manager","maps","entries","create",[string]$m.MainCertificateMapEntry,"--project=$project","--location=global","--map=$($m.CertificateMap)","--hostname=$main","--certificates=$($m.CanaryCertificateName)")
Write-GcloudPlan -Arguments @("certificate-manager","maps","entries","create",[string]$m.CanaryCertificateMapEntry,"--project=$project","--location=global","--map=$($m.CertificateMap)","--hostname=$canary","--certificates=$($m.CanaryCertificateName)")
Write-GcloudPlan -Arguments @("compute","target-https-proxies","update",[string]$m.HttpsProxyName,"--project=$project","--global","--certificate-map=//$('certificatemanager.googleapis.com')/projects/$project/locations/global/certificateMaps/$($m.CertificateMap)")
if(-not $Apply){Write-Output "PLAN COMPLETE — no GCP or Cloudflare state was changed.";return}
Assert-ApplyConfirmation -Apply $true -ExpectedProjectId $project -ConfirmProjectId $ConfirmProjectId
if([string]::IsNullOrWhiteSpace($env:CLOUDFLARE_API_TOKEN)-or[string]::IsNullOrWhiteSpace($env:MATCHBASE_CANARY_ORIGIN_ADMISSION_KEY)-or[string]::IsNullOrWhiteSpace($CloudflareZoneId)){throw "Apply requires in-memory Cloudflare credentials/key and exact zone ID."}
$proxy=Invoke-Gcloud -Arguments @("compute","target-https-proxies","describe",[string]$m.HttpsProxyName,"--project=$project","--global","--format=json")|ConvertFrom-Json
$knownClassic="/sslCertificates/$($m.CertificateName)"; if($proxy.certificateMap-and-not([string]$proxy.certificateMap).EndsWith("/certificateMaps/$($m.CertificateMap)")){throw "HTTPS proxy has an unrelated certificate map; mutation refused."};$unknown=@($proxy.sslCertificates|Where-Object{-not([string]$_).EndsWith($knownClassic)});if($unknown.Count){throw "HTTPS proxy has unrelated classic certificate attachments; mutation refused."}
$ownership=@{"matchbase-governed"="true";"matchbase-scope"="staging-canary-edge"}
$authorizationPreflight=@{};foreach($tuple in @(@($m.MainDnsAuthorization,$main),@($m.CanaryDnsAuthorization,$canary))){$name=[string]$tuple[0];$domain=[string]$tuple[1];if(Test-GcloudResource -Arguments @("certificate-manager","dns-authorizations","describe",$name,"--project=$project","--location=global")){$auth=Invoke-Gcloud -Arguments @("certificate-manager","dns-authorizations","describe",$name,"--project=$project","--location=global","--format=json")|ConvertFrom-Json;$rr=$auth.dnsResourceRecord;if($auth.domain-cne$domain-or$auth.type-cne"FIXED_RECORD"-or$auth.labels.'matchbase-governed'-cne"true"-or$auth.labels.'matchbase-scope'-cne"staging-canary-edge"-or$rr.type-cne"CNAME"-or$rr.name-cne"_acme-challenge.$domain."-or$rr.data-cnotmatch '^[a-z0-9-]+(?:\.[a-z0-9-]+)*\.authorize\.certificatemanager\.goog\.$'){throw "DNS authorization domain/type/record/ownership collision; mutation refused."};$authorizationPreflight[$name]=$auth}else{$authorizationPreflight[$name]=$null}}
$preflightCert=$null;if(Test-GcloudResource -Arguments @("certificate-manager","certificates","describe",[string]$m.CanaryCertificateName,"--project=$project","--location=global")){$preflightCert=Invoke-Gcloud -Arguments @("certificate-manager","certificates","describe",[string]$m.CanaryCertificateName,"--project=$project","--location=global","--format=json")|ConvertFrom-Json;Assert-ExactDomainSet -Actual @($preflightCert.managed.domains) -Expected @($main,$canary) -Description "Certificate Manager certificate";if($preflightCert.labels.'matchbase-governed'-cne"true"-or$preflightCert.labels.'matchbase-scope'-cne"staging-canary-edge"){throw "Certificate name/SAN/type/ownership collision; mutation refused."}}
$preflightMap=$null;if(Test-GcloudResource -Arguments @("certificate-manager","maps","describe",[string]$m.CertificateMap,"--project=$project","--location=global")){$preflightMap=Invoke-Gcloud -Arguments @("certificate-manager","maps","describe",[string]$m.CertificateMap,"--project=$project","--location=global","--format=json")|ConvertFrom-Json;if($preflightMap.labels.'matchbase-governed'-cne"true"-or$preflightMap.labels.'matchbase-scope'-cne"staging-canary-edge"){throw "Certificate-map ownership collision; mutation refused."}}
foreach($entry in @(@($m.MainCertificateMapEntry,$main),@($m.CanaryCertificateMapEntry,$canary))){if(Test-GcloudResource -Arguments @("certificate-manager","maps","entries","describe",[string]$entry[0],"--project=$project","--location=global","--map=$($m.CertificateMap)")){$existingEntry=Invoke-Gcloud -Arguments @("certificate-manager","maps","entries","describe",[string]$entry[0],"--project=$project","--location=global","--map=$($m.CertificateMap)","--format=json")|ConvertFrom-Json;if($existingEntry.hostname-cne$entry[1]-or@($existingEntry.certificates).Count-ne1-or-not([string]$existingEntry.certificates[0]).EndsWith("/certificates/$($m.CanaryCertificateName)")){throw "Certificate-map entry collision; mutation refused."}}}
$headers=@{Authorization="Bearer $($env:CLOUDFLARE_API_TOKEN)";"Content-Type"="application/json"};$api="https://api.cloudflare.com/client/v4/zones/$CloudflareZoneId";$ssl=Invoke-RestMethod Get "$api/settings/ssl" -Headers $headers;if($ssl.result.value-cne "strict"){throw "Cloudflare must already be Full (strict)."}
$governedAddress=(Invoke-Gcloud -Arguments @("compute","addresses","describe",[string]$m.AddressName,"--project=$project","--global","--format=value(address)")|Out-String).Trim();$preflightA=(Invoke-RestMethod Get "$api/dns_records?type=A&name=$canary" -Headers $headers).result;$preflightAAAA=(Invoke-RestMethod Get "$api/dns_records?type=AAAA&name=$canary" -Headers $headers).result;if($preflightAAAA.Count-ne0){throw "Explicit Canary AAAA record is prohibited because it can bypass the governed IPv4 origin."};if($preflightA.Count-gt1-or($preflightA.Count-eq1-and(-not$preflightA[0].proxied-or$preflightA[0].content-cne$governedAddress))){throw "Canary A identity/proxy/content drift; mutation refused."};$preflightRulesets=(Invoke-RestMethod Get "$api/rulesets?phase=http_request_late_transform" -Headers $headers).result;if($preflightRulesets.Count-ne1){throw "Exactly one late-transform ruleset must pre-exist."};$preflightRuleset=(Invoke-RestMethod Get "$api/rulesets/$($preflightRulesets[0].id)" -Headers $headers).result
$armorPreflight=Invoke-Gcloud -Arguments @("compute","security-policies","describe",[string]$m.SecurityPolicy,"--project=$project","--format=json")|ConvertFrom-Json;for($i=0;$i-lt$ranges.Count;$i++){$mainPriority=1000+$i;$mainExpression="inIpRange(origin.ip, '$($ranges[$i])') && request.headers['host'].lower() == '$main'";if(@($armorPreflight.rules|Where-Object{$_.priority-eq$mainPriority-and$_.action-ceq"allow"-and$_.match.expr.expression-ceq$mainExpression}).Count-ne1){throw "Original Cloud Armor rule drift; mutation refused."};$p=2000+$i;$e="inIpRange(origin.ip, '$($ranges[$i])') && request.headers['host'].lower() == '$canary'";$collision=@($armorPreflight.rules|Where-Object{$_.priority-eq$p});if($collision.Count-gt1-or($collision.Count-eq1-and($collision[0].action-cne"allow"-or$collision[0].match.expr.expression-cne$e))){throw "Canary Armor priority collision; mutation refused."}};if(@($armorPreflight.rules|Where-Object{$_.priority-eq2147483647-and$_.action-ceq"deny(403)"}).Count-ne1){throw "Armor default deny drift; mutation refused."}
if($null-ne$preflightMap){$entryList=Invoke-Gcloud -Arguments @("certificate-manager","maps","entries","list","--project=$project","--location=global","--map=$($m.CertificateMap)","--format=json")|ConvertFrom-Json;$actual=@($entryList.name|ForEach-Object{([string]$_).Split('/')[-1]}|Sort-Object);$expected=@(@($m.MainCertificateMapEntry,$m.CanaryCertificateMapEntry)|Sort-Object);if(($actual-join',')-cne($expected-join',')){throw "Certificate-map contains extra or missing entries; mutation refused."}}
if(@($proxy.sslCertificates).Count-eq1){$classic=Invoke-Gcloud -Arguments @("compute","ssl-certificates","describe",[string]$m.CertificateName,"--project=$project","--global","--format=json")|ConvertFrom-Json;Assert-ExactDomainSet -Actual @($classic.managed.domains) -Expected @($main) -Description "Known classic certificate"}
$authWork=@();foreach($tuple in @(@($m.MainDnsAuthorization,$main),@($m.CanaryDnsAuthorization,$canary))){$name=[string]$tuple[0];$auth=$authorizationPreflight[$name];if($null-eq$auth){Invoke-Gcloud -Arguments @("certificate-manager","dns-authorizations","create",$name,"--project=$project","--location=global","--domain=$tuple[1]","--type=FIXED_RECORD","--labels=matchbase-governed=true,matchbase-scope=staging-canary-edge")|Out-Null;$auth=Invoke-Gcloud -Arguments @("certificate-manager","dns-authorizations","describe",$name,"--project=$project","--location=global","--format=json")|ConvertFrom-Json};$rr=$auth.dnsResourceRecord;$found=(Invoke-RestMethod Get "$api/dns_records?type=CNAME&name=$($rr.name.TrimEnd('.'))" -Headers $headers).result;if($found.Count-gt1-or($found.Count-eq1-and($found[0].proxied-or$found[0].content.TrimEnd('.')-cne$rr.data.TrimEnd('.')))){throw "Existing Cloudflare authorization CNAME drift; mutation refused."};$authWork+=,[pscustomobject]@{Record=$rr;Found=$found}}
foreach($work in $authWork){if($work.Found.Count-eq0){$rr=$work.Record;$body=@{type="CNAME";name=$rr.name.TrimEnd('.');content=$rr.data.TrimEnd('.');ttl=300;proxied=$false;comment="MatchBASE Certificate Manager DNS authorization"}|ConvertTo-Json -Compress;Invoke-RestMethod Post "$api/dns_records" -Headers $headers -Body $body|Out-Null}}
$address=(Invoke-Gcloud -Arguments @("compute","addresses","describe",[string]$m.AddressName,"--project=$project","--global","--format=value(address)")|Out-String).Trim();$dns=(Invoke-RestMethod Get "$api/dns_records?type=A&name=$canary" -Headers $headers).result;$body=@{type="A";name=$canary;content=$address;ttl=1;proxied=$true;comment="MatchBASE governed EU canary"}|ConvertTo-Json -Compress;if($dns.Count-eq 0){Invoke-RestMethod Post "$api/dns_records" -Headers $headers -Body $body|Out-Null}elseif($dns.Count-eq 1){Invoke-RestMethod Put "$api/dns_records/$($dns[0].id)" -Headers $headers -Body $body|Out-Null}else{throw "Canary A identity is ambiguous."}
$rulesets=(Invoke-RestMethod Get "$api/rulesets?phase=http_request_late_transform" -Headers $headers).result;if($rulesets.Count-ne 1){throw "Exactly one late-transform ruleset must pre-exist."};$ruleset=(Invoke-RestMethod Get "$api/rulesets/$($rulesets[0].id)" -Headers $headers).result;$kept=@($ruleset.rules|Where-Object{$_.ref -cne "matchbase_canary_origin_admission"});$rule=@{ref="matchbase_canary_origin_admission";description="MatchBASE canary origin admission";expression="(http.host eq `"$canary`")";action="rewrite";action_parameters=@{headers=@{"MB-Origin-Admission"=@{operation="set";value=$env:MATCHBASE_CANARY_ORIGIN_ADMISSION_KEY}}};enabled=$true};$update=@{rules=@($kept)+@($rule)}|ConvertTo-Json -Depth 20 -Compress;$updated=Invoke-RestMethod Put "$api/rulesets/$($ruleset.id)" -Headers $headers -Body $update;if(-not$updated.success){throw "Cloudflare transform update failed."}
for($i=0;$i-lt$ranges.Count;$i++){$p=2000+$i;$e="inIpRange(origin.ip, '$($ranges[$i])') && request.headers['host'].lower() == '$canary'";if(Test-GcloudResource -Arguments @("compute","security-policies","rules","describe","$p","--project=$project","--security-policy=$($m.SecurityPolicy)")){$r=Invoke-Gcloud -Arguments @("compute","security-policies","rules","describe","$p","--project=$project","--security-policy=$($m.SecurityPolicy)","--format=json")|ConvertFrom-Json;if($r.action-cne"allow"-or$r.match.expr.expression-cne$e){throw "Armor collision at $p."}}else{Invoke-Gcloud -Arguments @("compute","security-policies","rules","create","$p","--project=$project","--security-policy=$($m.SecurityPolicy)","--action=allow","--expression=$e","--quiet")|Out-Null}}
if($null-eq$preflightCert){Invoke-Gcloud -Arguments @("certificate-manager","certificates","create",[string]$m.CanaryCertificateName,"--project=$project","--location=global","--domains=$main,$canary","--dns-authorizations=$($m.MainDnsAuthorization),$($m.CanaryDnsAuthorization)","--labels=matchbase-governed=true,matchbase-scope=staging-canary-edge")|Out-Null}
if($null-eq$preflightMap){Invoke-Gcloud -Arguments @("certificate-manager","maps","create",[string]$m.CertificateMap,"--project=$project","--location=global","--labels=matchbase-governed=true,matchbase-scope=staging-canary-edge")|Out-Null}
foreach($entry in @(@($m.MainCertificateMapEntry,$main),@($m.CanaryCertificateMapEntry,$canary))){$name=[string]$entry[0];if(Test-GcloudResource -Arguments @("certificate-manager","maps","entries","describe",$name,"--project=$project","--location=global","--map=$($m.CertificateMap)")){$current=Invoke-Gcloud -Arguments @("certificate-manager","maps","entries","describe",$name,"--project=$project","--location=global","--map=$($m.CertificateMap)","--format=json")|ConvertFrom-Json;if($current.hostname-cne$entry[1]-or@($current.certificates).Count-ne1-or-not([string]$current.certificates[0]).EndsWith("/certificates/$($m.CanaryCertificateName)")){throw "Existing certificate-map entry collision."}}else{Invoke-Gcloud -Arguments @("certificate-manager","maps","entries","create",$name,"--project=$project","--location=global","--map=$($m.CertificateMap)","--hostname=$($entry[1])","--certificates=$($m.CanaryCertificateName)")|Out-Null}}
$cert=Wait-CertificateManagerActive -TimeoutSeconds $CertificateTimeoutSeconds -IntervalSeconds $CertificatePollIntervalSeconds -Describe { Invoke-Gcloud -Arguments @("certificate-manager","certificates","describe",[string]$m.CanaryCertificateName,"--project=$project","--location=global","--format=json")|ConvertFrom-Json }
Assert-ExactDomainSet -Actual @($cert.managed.domains) -Expected @($main,$canary) -Description "Active Certificate Manager certificate"
Invoke-Gcloud -Arguments @("compute","target-https-proxies","update",[string]$m.HttpsProxyName,"--project=$project","--global","--certificate-map=//$('certificatemanager.googleapis.com')/projects/$project/locations/global/certificateMaps/$($m.CertificateMap)")|Out-Null
Write-Output "APPLY COMPLETE — DNS authorization stayed DNS-only; application A stayed proxied; unrelated attachments were not detached."
