[CmdletBinding()]
param([switch]$Apply,[string]$ConfirmProjectId="")
. (Join-Path $PSScriptRoot "Common.ps1")
$m=Get-MatchBaseStagingRegionMigration;$project=[string]$m.ProjectId;$region=[string]$m.TargetRegion;$matcher="matchbase-staging-eu-canary"
$negCreate=@("compute","network-endpoint-groups","create",[string]$m.CanaryNetworkEndpointGroup,"--project=$project","--region=$region","--network-endpoint-type=serverless","--cloud-run-service=$($m.CanaryWebService)","--quiet")
$backendCreate=@("compute","backend-services","create",[string]$m.CanaryBackendService,"--project=$project","--global","--load-balancing-scheme=EXTERNAL_MANAGED","--protocol=HTTP","--timeout=30s","--quiet")
$backendAdd=@("compute","backend-services","add-backend",[string]$m.CanaryBackendService,"--project=$project","--global","--network-endpoint-group=$($m.CanaryNetworkEndpointGroup)","--network-endpoint-group-region=$region","--quiet")
$backendPolicy=@("compute","backend-services","update",[string]$m.CanaryBackendService,"--project=$project","--global","--security-policy=$($m.SecurityPolicy)","--quiet")
$pathMatcher=@("compute","url-maps","add-path-matcher",[string]$m.UrlMap,"--project=$project","--global","--path-matcher-name=$matcher","--default-service=$($m.CanaryBackendService)","--quiet")
$hostRule=@("compute","url-maps","add-host-rule",[string]$m.UrlMap,"--project=$project","--global","--hosts=$($m.CanaryHostname)","--path-matcher-name=$matcher","--quiet")
foreach($arguments in @($negCreate,$backendCreate,$backendAdd,$backendPolicy,$pathMatcher,$hostRule)){Write-GcloudPlan -Arguments $arguments}
if(-not$Apply){Write-Output "PLAN COMPLETE — no canary route state was changed.";return}
Assert-ApplyConfirmation -Apply $true -ExpectedProjectId $project -ConfirmProjectId $ConfirmProjectId
$service=Invoke-Gcloud -Arguments @("run","services","describe",[string]$m.CanaryWebService,"--project=$project","--region=$region","--format=json")|ConvertFrom-Json;if(@($service.status.conditions|Where-Object{$_.type-ceq"Ready"-and$_.status-ceq"True"}).Count-ne1){throw "The exact EU canary service is not Ready."}
$before=Invoke-Gcloud -Arguments @("compute","url-maps","describe",[string]$m.UrlMap,"--project=$project","--global","--format=json")|ConvertFrom-Json;$mainBefore=[ordered]@{defaultService=[string]$before.defaultService;hostRules=@($before.hostRules|Where-Object{$_.pathMatcher-cne$matcher});pathMatchers=@($before.pathMatchers|Where-Object{$_.name-cne$matcher})}|ConvertTo-Json -Depth 20 -Compress
$foreignHost=@($before.hostRules|Where-Object{$_.hosts-ccontains$m.CanaryHostname-and$_.pathMatcher-cne$matcher});$foreignMatcher=@($before.pathMatchers|Where-Object{$_.name-ceq$matcher-and-not([string]$_.defaultService).EndsWith("/backendServices/$($m.CanaryBackendService)",[StringComparison]::Ordinal)});if($foreignHost.Count-or$foreignMatcher.Count){throw "Canary URL-map ownership collision; mutation refused."}
if(-not(Test-GcloudResource -Arguments @("compute","network-endpoint-groups","describe",[string]$m.CanaryNetworkEndpointGroup,"--project=$project","--region=$region"))){Invoke-Gcloud -Arguments $negCreate|Out-Null}
if(-not(Test-GcloudResource -Arguments @("compute","backend-services","describe",[string]$m.CanaryBackendService,"--project=$project","--global"))){Invoke-Gcloud -Arguments $backendCreate|Out-Null;Invoke-Gcloud -Arguments $backendAdd|Out-Null}
Invoke-Gcloud -Arguments $backendPolicy|Out-Null
if(@($before.pathMatchers|Where-Object{$_.name-ceq$matcher}).Count-eq0){Invoke-Gcloud -Arguments $pathMatcher|Out-Null}
if(@($before.hostRules|Where-Object{$_.hosts-ccontains$m.CanaryHostname-and$_.pathMatcher-ceq$matcher}).Count-eq0){Invoke-Gcloud -Arguments $hostRule|Out-Null}
$neg=Invoke-Gcloud -Arguments @("compute","network-endpoint-groups","describe",[string]$m.CanaryNetworkEndpointGroup,"--project=$project","--region=$region","--format=json")|ConvertFrom-Json;$backend=Invoke-Gcloud -Arguments @("compute","backend-services","describe",[string]$m.CanaryBackendService,"--project=$project","--global","--format=json")|ConvertFrom-Json;$after=Invoke-Gcloud -Arguments @("compute","url-maps","describe",[string]$m.UrlMap,"--project=$project","--global","--format=json")|ConvertFrom-Json
$mainAfter=[ordered]@{defaultService=[string]$after.defaultService;hostRules=@($after.hostRules|Where-Object{$_.pathMatcher-cne$matcher});pathMatchers=@($after.pathMatchers|Where-Object{$_.name-cne$matcher})}|ConvertTo-Json -Depth 20 -Compress
if($neg.cloudRun.service-cne$m.CanaryWebService-or@($backend.backends).Count-ne1-or-not([string]$backend.backends[0].group).EndsWith("/networkEndpointGroups/$($m.CanaryNetworkEndpointGroup)")-or-not([string]$backend.securityPolicy).EndsWith("/securityPolicies/$($m.SecurityPolicy)")-or$mainAfter-cne$mainBefore-or@($after.hostRules|Where-Object{$_.hosts-ccontains$m.CanaryHostname-and$_.pathMatcher-ceq$matcher}).Count-ne1-or@($after.pathMatchers|Where-Object{$_.name-ceq$matcher-and([string]$_.defaultService).EndsWith("/backendServices/$($m.CanaryBackendService)")}).Count-ne1){throw "Canary route verification failed or the main route changed."}
Write-Output "APPLY COMPLETE — the isolated EU canary route is live and the main default route is unchanged."
